### ISSUE TITLE
Darstellung "Übersicht Briefe" (bzw. "Gesamtkorpus")

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#1]
- Spalte Dokument streichen und dafür die ganze Zeile zum Anklicken, sodass man auf das Dokument kommt?

- 1 Spalte sollte sein: Titel: ID; Inhalt: Kürzel aus Anstalt & Aktennummer & Nachname Patient, z.B. kfb38s (= Kaufbeuren, Akte 3, Nachname beginnt mit S), Info findet sich bei xml:id="kfb38s", einfach die ID hier anzeigen, nach dieser sollte die ganze Tabelle sortiert sein

- 2 Spalte: Titel: Patient; Inhalt: Vorname/Nachname Patient (ist innerhalb einer Akte immer gleich, da jeder Patient eine Akte hat, Name findet sich bei `<particDesc><persName>`)

- 3 Spalte: Geburt (lassen wie es ist)

- 4 Spalte: Eintritt (lassen wie es ist)

- 5 Spalte: Austritt (lassen wie es ist)

- 6 Spalte: Titel: Tod in Anstalt; Inhalt bei `<death cert="unknown">`: nein [wenn Patienten entlassen wurden, weiß man das Todesjahr nicht]; Inhalt bei `<death when="1xxx">`: ja

- Jetzige Spalte "Wohnort" ist eigentlich der Schreibort, könnte man drinnen lassen und nach unten schieben nach Spalte 9 Datum

[Beruf/Wohnort/Familienstand/Religion... Da wir ja auch die Aktenübersicht haben, ist fraglich, wie viele von den Metadaten ab Spalte 3 zu den Patienten hier schon erscheinen sollten... die Infos ab den folgenden Spalten sind aber wichtig, weil sie nur für den jeweiligen Text gelten]

- 7 Spalte: Titel: Texttyp; Inhalt: dies geht leider nur aus dem Dateinamen klar hervor; es gibt 4 Brieftypen: pp = Privatbrief eines Patienten; po = offizieller Brief eines Patienten; ap = Privatbrief von außen; ao = offizieller Brief von außen; daneben sonstige Textsorten, sollten immer mit "so" eingeleitet sein; Inhalt der Spalte könnte einfach das Kürzel sein, das an anderer Stelle der Website (oder sogar bei Mausover) erklärt wird

- 8 Spalte: Titel: Schreiber; Inhalt: Vorname/Nachname des Schreibers, findet sich bei `<creation><pers Name type="sender">`

- 9 Spalte: Datum des Textes

- 10 Spalte etc.: vielleicht knapp Infos zu Seitenzahl und - leider nicht im XML - Wortzahl

**Comment by haoess** [comment]
> * Spalte Dokument streichen und dafür die ganze Zeile zum Anklicken, sodass man auf das Dokument kommt?

Ganze Zeile einfacher Klick: Würde ich (erstmal) nicht machen, da es z. B. Copy&Paste erschwert. Aber Doppelklick auf die Zeile funktioniert nun.

> * 1 Spalte sollte sein: Titel: ID; Inhalt: Kürzel aus Anstalt & Aktennummer & Nachname Patient, z.B. kfb38s (= Kaufbeuren, Akte 3, Nachname beginnt mit S), Info findet sich bei xml:id="kfb38s", einfach die ID hier anzeigen, nach dieser sollte die ganze Tabelle sortiert sein

:heavy_check_mark: 

> * 2 Spalte: Titel: Patient; Inhalt: Vorname/Nachname Patient (ist innerhalb einer Akte immer gleich, da jeder Patient eine Akte hat, Name findet sich bei `<particDesc><persName>`)

:heavy_check_mark: 

> * 3 Spalte: Geburt (lassen wie es ist)

:heavy_check_mark: 

> * 4 Spalte: Eintritt (lassen wie es ist)

:heavy_check_mark: 

> * 5 Spalte: Austritt (lassen wie es ist)

:heavy_check_mark: 

> * 6 Spalte: Titel: Tod in Anstalt; Inhalt bei `<death cert="unknown">`: nein [wenn Patienten entlassen wurden, weiß man das Todesjahr nicht]; Inhalt bei `<death when="1xxx">`: ja

:heavy_check_mark: 

> * Jetzige Spalte "Wohnort" ist eigentlich der Schreibort, könnte man drinnen lassen und nach unten schieben nach Spalte 9 Datum

:heavy_check_mark: 
 
> [Beruf/Wohnort/Familienstand/Religion... Da wir ja auch die Aktenübersicht haben, ist fraglich, wie viele von den Metadaten ab Spalte 3 zu den Patienten hier schon erscheinen sollten...

Hab ich erstmal dringelassen bis die Aktenansicht kommt.

> die Infos ab den folgenden Spalten sind aber wichtig, weil sie nur für den jeweiligen Text gelten]
> 
> * 7 Spalte: Titel: Texttyp; Inhalt: dies geht leider nur aus dem Dateinamen klar hervor; es gibt 4 Brieftypen: pp = Privatbrief eines Patienten; po = offizieller Brief eines Patienten; ap = Privatbrief von außen; ao = offizieller Brief von außen; daneben sonstige Textsorten, sollten immer mit "so" eingeleitet sein; Inhalt der Spalte könnte einfach das Kürzel sein, das an anderer Stelle der Website (oder sogar bei Mausover) erklärt wird

:heavy_check_mark: 

> * 8 Spalte: Titel: Schreiber; Inhalt: Vorname/Nachname des Schreibers, findet sich bei `<creation><pers Name type="sender">`

:heavy_check_mark: 

> * 9 Spalte: Datum des Textes

:heavy_check_mark: 

Ein kürzerer Spaltentitel wäre hier gut.

> * 10 Spalte etc.: vielleicht knapp Infos zu Seitenzahl und - leider nicht im XML - Wortzahl

:heavy_check_mark:
