### ISSUE TITLE
Darstellung <add> <seg ana="#pic">[Stern]</seg> </add>

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#10]
Wenn eine Zeichnung in einen add-Tag eingebettet ist, erscheint nicht der Inhalt der Zeichnung (Stern), sondern das Mouseover "Einfügung", z.B. hier https://deutschestextarchiv.github.io/copadocs/kfb_00373_n_m_rotgerber_1842_1882_po1-so1/kfb_00373_n_so-concertbericht_1882_06_26-28.html

**Comment by haoess** [comment]
Mit 61cfb8b701 wird die Beschreibung der Zeichnung nun als Tooltip unterhalb angezeigt. Wir haben hier mehrere Informationen: `<add>` innerhalb von `<add place="margin">` und darin dann `<seg ana="#pic">[Stern]</seg>`.
