### ISSUE TITLE
Wohnort

### ISSUE THREAD

**Issue by nina-bro** [deutschestextarchiv/copadocs#11]
Wir haben für den Geobrowser die TEI-Struktur nochmal abgeändert, sodass der Wohnort jetzt 
```
<residence>
<geo decls="#WGS">48.0514973 10.8737728</geo>
Landsberg
</residence>
```
so angegeben wird. 
In der Briefübersicht sollen die Koordinaten aber nicht mitangezeigt werden.

**Comment by haoess** [comment]
In Liste korrigiert. Sollen die Koordinaten in der Metadateneinzelansicht verlinkt werden? Wenn ja, wohin?

**Comment by maschiegg** [comment]
Danke! Daran habe ich noch gar nicht gedacht, dass man hier die Koordinaten auch nutzen könnte. In den Geobrowser zu den anderen Punkten kann man wohl nicht verlinken, aber wenn man ganz einfach auf eine Karte wie Open Street Map verlinken könnte, wäre das vielleicht hilfreich (muss aber nicht sein, wenn es zu aufwändig ist).

**Comment by haoess** [comment]
Ist gemacht.
