### ISSUE TITLE
Detailansicht P-Akte: Neuer Tab

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#17]
Klickt man bei https://deutschestextarchiv.github.io/copadocs/patientenakten.html auf einen Link auf "Akte" zur Öffnung in einem neuen Tab bzw. mit mittlerer Maustaste, dann erscheint die Copadocs-Startseite.

Außerdem "springt" die Ansicht der Detailansicht P-Akte nach unten, wenn man sie öffnet. Sie sollte sich ja eigentlich oben öffnen.

**Comment by haoess** [comment]
mit 62586f2e behoben
