### ISSUE TITLE
Patientenakten-Ansicht: Metadaten

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#18]
Übersicht:
1. Spalte ganz links sollte nicht "Archiv", sondern "Anstalt" sein, wir haben für jede psychiatrische Anstalt ein Kürzel vergeben, die Westfalen-Anstalten sind z.B. alle in einem Archiv aufbewahrt. Toll wäre hier ein Mouseover mit diesen Infos:
dor = Dortmund-Aplerbeck
gut = Gütersloh
kfb = Kaufbeuren-Irsee
lip = Lippstadt
mrs = Marsberg
mun = Münster
war = Warstein
[kommt noch:] ham = Hamburg

2. statt "Wohnort" hier einfach "Herkunft", da recht unsystematisch (im Geobrowser haben wir das systematischer gemacht)

3. wichtig wäre noch die Info "Diagnose", das ist aber oft eine recht umfangreiche Spalte; man könnte Beruf etwas enger machen, evtl. Familienstand hier nicht einblenden, da recht irrelevant; wenn die Diagnose-Spalte dann 2-3 Zeilen hat, ist das denke ich auch ok

Detailansicht:
Die Diagnose sollte unbedingt noch dargestellt werden, evtl. in der untersten Zeile, wobei die Info die Breite der 3 Spalten einnehmen könnte

**Comment by haoess** [comment]
Alles umgesetzt, den Familienstand hab dringelassen, geht schon so, finde ich.

Interessant wäre vielleicht noch die Geschlechtsangabe – hier (oben rechts neben dem Namen), aber und auch vor allem in der Korpusübersicht – und dort würde ich dann lieber die Angabe zur Herkunft weglassen, weil man danach eh nicht sinnvoll sortieren/filtern kann.

**Comment by maschiegg** [comment]
**Korpusansicht/Patientenaktenansicht**

- Die Diagnose sollte auch noch in beiden Ansichten sein, das ist eine der einzigartigen Metadaten des Korpus, nach denen man suchen wird. Auch wenn sie recht unsystematisch sind, kann man mit der Suche doch viele gleiche Erkrankungen finden.

- Dafür könnte die Spalte Beruf etwas schmaler sein oder die Schriftgröße noch etwas verkleinern? Auch ist bei Patientenakten die Spalte Beruf breiter als in der Korpusansicht. [Vermutlich entsteht die Spaltengröße ja automatisch]

[vermutlich technisch nicht umsetzbar:] Statt "Tod in der Anstalt" könnte man auch hinter die Austritt-Zahl ein Kreuz-Symbol machen (Tod ja) oder weglassen (Tod nein) und bei Mouseover steht dann beim Kreuz "Tod in der Anstalt". Denn das Wort "Austritt" ist ja auch nicht ganz optimal, wenn die Person in der Anstalt stirbt.

Herkunft ist auch sehr wichtig und sollte überall drinnen bleiben, man kann z.B. nach "Augsburg" suchen und kriegt dann schon schöne Ergebnisse.

**Detailansicht Patientenakte**
- Ich habe die Anstaltsnamen in der archive-name.xsl erweitert/korrigiert, jetzt erscheint die volle Info im ersten Feld; dieses sollte von "Anstalt" auf "Provenienz" umbenannt werden (leider ist das Feld jetzt oft 4-5-zeilig); bei Mouseover erscheint jetzt "undefined", kann gelöscht werden
- Bitte oben ergänzen: "Eltern" und das entsprechende Feld dort einfügen
- Bei den Briefen ergänzen: "Adressat"
- Bei kleinen Monitoren/Handy schiebt sich das oben so zusammen, dass es unlesbar wird. Können die einzelnen Punkte (Anstalt, Akte etc.) untereinander dargestellt werden, wenn eine Mindestbreite des Monitors unterschritten wird?

**Comment by haoess** [comment]
Vorschlag für die Detailansicht Patientenakte, ich habe die Felder nochmal umsortiert und weitere ergänzt.

![image](https://github.com/deutschestextarchiv/copadocs/assets/44678/1a227f60-a3e2-47ac-88b2-904152cff147)

**Comment by maschiegg** [comment]
Die Ansicht zur Patientenakte sieht wunderbar aus! Evtl. wird Beruf manchmal etwas eng, man könnte auch Religion an die Stelle von Eltern tun und Eltern unter Geburt (Eltern braucht manchmal auch mehr Platz); dann Familienstand und Beruf nach links schieben, sodass Beruf mehr Platz hat?

**Comment by maschiegg** [comment]
Jetzt gibt es noch Metadaten "Verpflegungsklasse" zu den meisten Patienten (1, 2 oder 3), hat Frau Brolich heute bei allen XML-Dateien ergänzt. Das könnte man noch einblenden, z.B. als 3. Spalte nach Eintritt und Austritt?

**Comment by haoess** [comment]
alles umgesetzt
