### ISSUE TITLE
Detailansicht Patientenakte Texttyp so

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#19]
Bei der Detailansicht Patientenakte könnte statt nur Texttyp so die von uns vergebene Textsortenbezeichnung im Dateinamen stehen. Diese findet sich direkt nach so, z.B. "so-lebenslauf" hier https://deutschestextarchiv.github.io/copadocs/patientenakten.html#kfb-1356
oder "so-aufzeichnungen" hier https://deutschestextarchiv.github.io/copadocs/patientenakten.html#dor-2499%20(K.%2060)

Eine optimale Darstellung wäre "so (Lebenslauf)", d.h. mit Leerzeichen, in Klammern und Großschreibung der Textsorte. 

Manchmal fehlt die Textsortenangabe (wenn z.B. nicht klassifizierbar), dann könnte das Feld leerbleiben.

**Comment by haoess** [comment]
Ist nun so, wird aber aus `/TEI/teiHeader/profileDesc/textDesc/domain` übernommen. (Wertvolle) Informationen im Dateinamen zu kodieren ist generell keine gute Idee, außerdem funktioniert das mit der Orthografie (G/K-Schreibung) da nicht (*erinnerungen-unsortiert*, *beiblatt-zum-lebenslauf*).

**Comment by maschiegg** [comment]
Wir könnten die Infos auch ins XML aufnehmen, es ist eine überschaubare Menge an so-Texten
