### ISSUE TITLE
Zitationshinweis und Namensnennung

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/copadocs#2]
An jedem Dokument in HTML-Darstellung wäre ein Zitationshinweis gut, ich würde ihn vermutlich als eigenen Button neben "Metadaten" und "TEI-XML" platzieren. Dafür bräuchte ich Input.

Außerdem distribuieren wir alle Daten als CC BY-SA – das "BY" (Namensnennung) sollte als Hilfe für Nutzende einen Hinweis bekommen, welcher "Name" da genau bei Wiederverwendung genannt werden soll.

**Comment by maschiegg** [comment]
Ein Zitationshinweis klingt sinnvoll und der Ort erscheint mir gut gewählt. Ob mein Name und das Projekt nötig sind, weiß ich nicht, die Quellenangabe zum Archiv aber auf jeden Fall:
Evtl. 
Schiegg, Markus (Hg.): CoPaDocs - Korpus historischer Patiententexte. https://deutschestextarchiv.de/copadocs. Quelle aus: [ARCHIVNAME*], Patientenakte [AKTENNUMMER], [VORNAME PATIENT ABK. NACHNAME], Text von [XX], [DATUM]

*Archivname: bei kfb = Archiv des Bezirkskrankenhauses Kaufbeuren
bei war, mun, len = LWL-Archivamt für Westfalen, Münster (Best. 656)
ham = Staatsarchiv Hamburg, Bestand Staatskrankenanstalt Langenhorn (352-8/7, Abl. 1995/2)
... alle Archive teile ich Ihnen noch mit, die genauen Bestände muss ich noch heraussuchen

**Comment by maschiegg** [comment]
Wird bei "BY" (Namensnennung) der Projektverantwortliche genannt? Dann sollte da mein Name erscheinen?
