### ISSUE TITLE
Felder mit fehlender Informationsangabe

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/copadocs#22]
Wir haben derzeit diese Varianten, fehlende Informationen zu markieren:

1. leeres Element
2. "n.a."
3. "k.A."

Das betrifft sowohl komplette als auch Teilangaben wie in `<persName type="addressee">Frau und Kinder: n.a. <surname>F.</surname></persName>`.

Gut wäre es, wenn diese Angabe – so weit möglich – einheitlich wären, und zwar:

1. Maschinenlesbarkeit. Dafür ist z. B. `<settlement type="received"/>` viel besser geeignet als `<settlement type="received">n.a.</settlement>`. Heißt: Wenn der komplette Elementinhalt keine richtige Angabe enthält: das Element leer lassen.
2. "n.a." vs. "k.A.": Ersteres ist eine englische Abkürzung und passt nicht ganz so recht in die sonst komplett deutschsprachigen Metadaten. "k.A." ist Abkürzung für 2 Wörter und muss typografisch korrekt mit Leerzeichen geschrieben werden: "k. A."

Wenn es keinen Widerspruch gibt, würde ich das Korpus einmal komplett dahingehend anpassen. Kann aber auch sein, dass ich was übersehen habe …

**Comment by maschiegg** [comment]
Ok, können Sie gerne anpassen!
Bei `<persName type="addressee">Frau und Kinder: n.a. <surname>F.</surname></persName>` wird das n.a. dann einfach zu einem k. A. und der Rest bleibt?

**Comment by haoess** [comment]
> Bei `<persName type="addressee">Frau und Kinder: n.a. <surname>F.</surname></persName>` wird das n.a. dann einfach zu einem k. A. und der Rest bleibt?

Genau so ist es.

**Comment by haoess** [comment]
Alles so weit umgesetzt. Bei den Datumsangaben sind 3 Werte aufgefallen:

* kfb_01745_w_f_schneidergehilfensehefrau_1848_1882-89_pp6-po2-ao1/kfb_01745_w_pp_1882_06_31.xml: `<date type="sent">31.06.1882</date>`

* kfb_02058_w_m_muellergeselle_1842_1875-94_pp12-po9-ap1-ao1-so2/kfb_02058_w_po_1891_02_29.xml: `<date type="sent">29.02.1891</date>`

* kfb_02226_v_f_schuhmachersehefrau_1838_1885-1918_pp19/kfb_02226_v_pp_1898_06_31.xml: `<date type="sent">31.06.1898</date>`

Vermutlich sind das keine Transkriptionsfehler, aber diese Daten sind nicht valide. Mit 9f40225 habe ich das so gelöst: den geschriebenen Text lassen wir, für die Maschinenlesbarkeit verkürzen wir auf den Monat.

**Comment by maschiegg** [comment]
Super, danke! Die Patienten irren sich natürlich auch oft im Datum...

**Comment by maschiegg** [comment]
...die when-Info haben aber nur genaue Daten erhalten?
Z.B. bei https://deutschestextarchiv.github.io/copadocs/patientenakten.html#kfb-828
'<date type="sent" when="1870-09-27">27.09.1870</date>'
versus
'<date type="sent">xx.xx.1870</date>'
Beim zweiten Fall weiß man ja immerhin das Jahr.

**Comment by maschiegg** [comment]
Es gibt im TEI manchmal Angaben ganz ohne Jahr, man kann diese aber auf den Aufenthaltszeitraum eingrenzen. Z.B. bei der Datei:
[kfb_00539_h_f_ministerialsekretaerstochter_1820_1858-61_pp4-ao2/kfb_00539_h_pp_ca1858-61_05_15.xml](https://deutschestextarchiv.github.io/copadocs/data/kfb_00539_h_f_ministerialsekretaerstochter_1820_1858-61_pp4-ao2/kfb_00539_h_pp_ca1858-61_05_15.xml)
Hier steht der Aufenthaltszeitraum ja im Dateinamen (1858-61), leider aber nicht im XML.

Sie haben das im commit fd89efb so korrigiert:
alt: `<date type="sent">15–16.05.xx</date>`
korrigiert zu: `<date type="sent" when="--05-15">15–16.05.xxxx</date>`

Man könnte aber machen?
`<date type="sent" notBefore="1858" notAfter="1861">`
Denn die Tage sind weniger aussagekräftig als die Jahre, man sucht eher mal Briefe um 1860 als Briefe vom Mai.

**Comment by haoess** [comment]
Ja, alles richtig, und nun so umgesetzt. Angezeigt wird weiterhin der Textinhalt des `<date>`-Elements, sortiert wird nun aber nach den Attributwerten (zuerst `@when`, falls vorhanden, dann `@notBefore`, dann `@notAfter`).
