### ISSUE TITLE
Kodierungsfehler in kfb_00103_p_po_ca1853-65_a.xml

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/copadocs#23]
In [kfb_00103_p_po_ca1853-65_a.xml](https://deutschestextarchiv.github.io/copadocs/data/kfb_00103_p_m_candidatdertheologie_1819_1853-65_pp7-po12-so2/kfb_00103_p_po_ca1853-65_a.xml) gibt es einen Kodierungsfehler in folgender Zeile:

```xml
begnagtigte bin das es wahr ist</hi> die h</p>oche
```

Dieses `</p>` dort stimmt nicht, damit ist das Dokument auch nicht mehr TEI-valide. Leider kann ich es nicht selbst korrigieren, weil ich den Text nicht lesen kann.

**Comment by maschiegg** [comment]
Es ist die Datei https://deutschestextarchiv.github.io/copadocs/kfb_00844_h_f_zieglerstochter_1844_1886-97_pp38-po8-ap1-ao1-so1/kfb_00844_h_pp_ca1886-97_05_16.html

Das `</p>` muss nach das letzte Wort "Zieglertochter" geschoben werden.

Ich korrigiere das jetzt nicht schnell im XML, sonst dauert es wieder 20 Minuten, bis die Seite aufgebaut ist...
