### ISSUE TITLE
Rest von Issue 6: Anordnung Einzelbriefanzeige

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#26]
Rechts neben dem Text ist noch eine hellgraue Box. Ist diese nötig oder könnte man den Platz besser für Text/Faksimile nutzen? Das Faksimile verschwindet nämlich schon, wenn die Monitorbreite kleiner als ca. 1000 Pixel wird.

Das Faksimile könnte gerne auch ein bisschen größer sein, wenn die Box entfernt und der Text etwas nach rechts verschoben werden könnte.

**Comment by haoess** [comment]
Ist nun besser gelöst.
