### ISSUE TITLE
veränderte Ordnernamen, Verlinkung Facsimiles

### ISSUE THREAD

**Issue by nina-bro** [deutschestextarchiv/copadocs#28]
Wir haben bei ein paar Akten nochmal die Ordnernamen geändert, weil die Zählung der Textsorten falsch war. Jetzt stimmt aber die Verlinkung auf die Facsimiles nicht mehr - könnten Sie die Ordnernamen entsprechend abändern?

Es handelt sich um folgende Akten (mit folgenden neuen Ordnernamen):
kfb77: kfb_00077_j_f_klaviersfabrikantfrau_1792_1850-51_pp2-po1-ap2-ao26
kfb825: kfb_00825_g_f_bataillonsarztgattin_1826_1864-70_pp1-po2
kfb844: kfb_00844_h_f_zieglerstochter_1844_1886-97_pp38-po7-ap1-ao1-so1
kfb936: kfb_00936_g_m_schneider_1847_1883-1901_pp14-po82-ao1-so2
kfb966: kfb_00966_b_m_buchhalter_1851_1877-1904_pp19-po4-ao8-so5
kfb1623: kfb_01623_g_m_zimmergeselle_1851_1874-1905_pp14-po6-so1
kfb1628: kfb_01628_s_m_tageloehner_1863_1892-1908_pp1-po5
kfb1720: kfb_01720_w_m_oekonomenssohn_1861_1886-1917_pp5-po2-ap1-ao13-so1
kfb1945: kfb_01945_h_m_schneidergeselle_1830_1854-91_pp5-po4-ap1-ao2
kfb2229: kfb_02229_w_m_zeichner_1880_1905-18_pp4-ap1-ao1
kfb2245: kfb_02245_r_f_soeldnerstochter_1882_1899-1918_pp20-po1-ap2-ao7
kfb2452: kfb_02452_b_m_hauptmann_1814_1853-55_pp1-po12-so2
kfb2807: kfb_02807_h_m_hausierer_1855_1888-1921_ap1-ao1-so1
kfb2882: kfb_02882_f_m_muellermeister_1849_1884-1924_pp12-po4-so1
kfb2936: kfb_02936_s_m_tageloehner_1872_1922-27_pp15-po20-ap1-ao2-so5
lip2509: lip_02509_n_f_fuersorgezoegling_1899_1913-33_pp9-po15-ap2-so2

**Comment by haoess** [comment]
Ist nun alles angepasst.

**Comment by nina-bro** [comment]
bitte für ham20087 auch noch ändern:
ham_20087_s_m_klempner_1889_1935-49_pp2-po9-so1

**Comment by haoess** [comment]
:heavy_check_mark:
