### ISSUE TITLE
<add place="…">

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/copadocs#30]
Die Werte für `<add place="…">` sind wie folgt vergeben:

* above
* below
* bottom
* inline
* inlnir¹
* inspace³
* margin
* margin left²
* margin_left²
* margin right²
* margin_right²
* marign right¹²
* opposite
* top

¹ sieht mir nach Fehler aus
² sollte vereinheitlicht werden: `margin_left` bzw. `margin_right` (also mit Unterstrich)
³ hierfür bräuchte ich Dokumentation, was das bedeutet – wird nur in [1 Dokument](https://deutschestextarchiv.github.io/copadocs/kfb_02245_r_f_soeldnerstochter_1882_1899-1918_pp20-po1-ap2-ao7/kfb_02245_r_pp_1911_08_19.html) benutzt

**Comment by maschiegg** [comment]
(1) zu inline ändern
(2) margin haben wir eigentlich nicht subklassifiziert, d.h. left und right dürften eigentlich gar nicht erscheinen. @nina-bro bitte prüfen, wie oft das erscheint und wenn nur in Einzelfällen, dann ändern zu `<add place='margin'>`
(3) ändern zu `<add>`

Diese Fälle existieren laut unserer Dokumentation:
`<add place='above'>: interlineare Einfügung darüber
<add place='below'>: interlineare Einfügung darunter
<add place='top'>: Einfügung am oberen Seitenrand
<add place='bottom'>: Einfügung am unteren Seitenrand
<add place='margin'>: Einfügung am Rand links oder rechts
<add place='inline'>: Einfügung auf der Zeile (z.B. zwischen 2 Wörtern)
<add place='opposite'>: Zusatz, der auf anderer Briefseite weitergeht
<add>: nicht näher definierte Einfügung, am besten wie ‘above’ behandeln`
