### ISSUE TITLE
Werte für xml:lang

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/copadocs#32]
Die Werte in `@xml:lang` sollten einheitlich kodiert sein. Hier die Liste für Vorkommen im Element `<foreign>`:

|Vorkommen|Ist-Wert|Soll-Wert bzw. Vorschlag nach [ISO 639-3](https://de.wikipedia.org/wiki/ISO_639#ISO_639-3)|
|--------------:|-------|-------|
|176|frz|fra|
|126|lat|lat|
|31|fr|fra|
|12|ital|ita|
|12|engl|eng|
|8|russ|rus|
|8|en|eng|
|6|hebr|heb|
|2|la|lat (?)|
|2|it|ita (?)|
|2|eng|eng|
|1|nl|nld (?)|
|1|griech|ell (wenn heutiges Griechisch gemeint ist)

Am Wurzelelement `<TEI>` hängt das auch und ist einheitlich als `@xml:lang="de"` kodiert. Das kann so bleiben.

**Comment by maschiegg** [comment]
- zu "griech": wird altgriechisch sein, dann "grc" laut ISO
- bei "la" bitte prüfen, ob lateinisch
- dann alle gemäß ISO ändern
