### ISSUE TITLE
@mimeType

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/copadocs#33]
Im Projekt benutzen wir das Attribut `@mimeType` am Element `<graphic>`. Dieses sollte einheitlich kodiert sein. Da wir nur auf JPEG-Dateien verweisen, ist nur ein Wert zulässig: `image/jpeg`.

Der Wert `image/jpg` (11449 Vorkommen) ist [kein gültiger MIME-Type](https://www.rfc-editor.org/rfc/rfc2046.html), und im Dokument `kfb_00080_a_m_krankenwaerter_1901_1917-31_pp2-po110-ao7-so11/kfb_00080_a_so-aufmunterung-gebet_ca1917-31.xml` ist `image/jpef` wohl ein Vertipper.

**Comment by maschiegg** [comment]
@nina-bro bitte zu jpeg ändern; Vertipper habe ich ausgebessert
