### ISSUE TITLE
<hi style="…"> → <hi hand="…">

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/copadocs#36]
`<hi style="…">` kommt nur in Verbindung mit `@rendition="u"` vor. Die Werte für `@style`:

|Vorkommen|Wert|
|----:|----|
|1979|arzt|
|140|arzt2|
|123|hand2|
|43|hand4|
|29|arzt1|
|28|hand3|
|21|patient|
|13|arzt3|
|8|hand5|
|6|crayon|
|5|pencil|
|3|verwalter2|
|1|ink|
|1|arzt5|
|1|arzr|

Vermutlich kann das alles als `<hi hand="…">` kodiert werden, denn `@style` ist [eher dafür gedacht](https://guidelines.tei-c.de/en/html/ref-att.global.rendition.html#tei_att.style):

> contains an expression in some formal style definition language which defines the rendering or presentation used for this element in the source text

**Comment by maschiegg** [comment]
@nina-bro Bitte zu "hand" ändern (und Tippfehler letzte Zeile "arzr" zu "arzt" ändern)
