### ISSUE TITLE
<seg rend="…">

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/copadocs#38]
2 Vorkommen von `<seg rend="…">`, die mir wie Fehltaggings aussehen:

|Dokument|Tagging|
|----|----|
|`kfb_01419_g_m_regenschirmfabrikant_1811_1875_pp2_po1_ao7/kfb_01419_g_ao_1875_06_21.xml`|`<seg rend="#salute">`|
|`kfb_01243_r_m_ordenspriester_1833_1864-66_po1-ao1-so2/kfb_01243_r_po_1864_xx_xx.xml`|`<seg rend="rend">`|

**Comment by maschiegg** [comment]
zu `<seg ana="#salute">` (kfb1419); bei kfb1243 gelöscht
