### ISSUE TITLE
Einzelbrief: Anzeige oberste Zeile

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#4]
Bei der Ansicht eines Einzelbriefs wäre in der obersten Zeile statt z.B.
Start / Anna H. / 21.10.1857
besser:
Start / kfb-102 (Fritz von M.) / ao von Anna H. / 22.12.1856
[mit Mouseover bei ao = offizieller Brief von außen]

**Comment by maschiegg** [comment]
... und bei "kfb-102 (Fritz von M.)" könnte dann ein Link auf die Patientenakte dieses Schreibers bei der Patientenaktenansicht sein

**Comment by haoess** [comment]
Link auf die Patientenakte aus den einzelnen Briefen heraus: :heavy_check_mark:
