### ISSUE TITLE
Teilweise seltsame Umbrüche

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#40]
Manche Dateien zeigen seltsame Zeilenumbüche, z.B.:
https://deutschestextarchiv.github.io/copadocs/kfb_02162_b_m_apotheker_1833_1881-85_pp2-po1/kfb_02162_b_po_ca1881-85.html

https://deutschestextarchiv.github.io/copadocs/kfb_02162_b_m_apotheker_1833_1881-85_pp2-po1/kfb_02162_b_pp_1881_06_03.html
Kommt das von der Verschachtelung von Tags?

**Comment by Zatu1337** [comment]
Grüße! Was hast du denn bei deinen funktionierenden Dateien anders gemacht?
Ich habe folgendes gefunden: -> Deine Textzeilen stehen in einem <span> tag mit der class="tei-hi" die sorgt wohl standardmäßig für eine verschiebung "margin-right: 815px;" ; allerdings ist der bereich worin der text steht ohne eine höhenangabe und nur 500px weit/lang). 
Außerdem die Tags selbst worin einzelne Teile gebunden sind.
'tr' tag| Defines a row in a table
-- | --
"td"  tag| Defines a cell in a table
Das könnte zu einzelnen Worten in einer Reihe führen.

**Comment by maschiegg** [comment]
Ich konnte die Probleme lösen, die wohl nur bei diesen Dateien auftraten, weil der  class="tei-hi"-Tag zu lang/verschachtelt war, habe es etwas umformatiert und jetzt passt alles!
