### ISSUE TITLE
(nahezu) Duplikat

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/copadocs#44]
Diese beiden Dokumente sind nahezu identisch:

1. `kfb_01868_h_m_buchbindermeister_1865_1893-1902_pp5-po2-ap9-ao14-so15/kfb_01868_h_so-erlebnisbericht_ca1893-1902.xml`
2. `kfb_01868_h_m_buchbindermeister_1865_1893-1902_pp5-po2-ap9-ao14-so15/kfb_01868_h_so-erlebnisbericht_ca1893-1902_FRAGMENT.xml`

**Comment by maschiegg** [comment]
Stimmt, das ohne Endung _FRAGMENT ist die ältere Version und kann gelöscht werden.

Der Ordnername müsste dann ...so14 lauten.
