### ISSUE TITLE
Silbentrennung Zeilenende

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#5]
Unsere TEI-Codierung der Silbentrennung ist etwas "ungewöhnlich". Das hier ist ein normaler Zeilenumbruch ohne Trennstrich:
``` 
viele Fremde
<lb break="yes"/>
niedrer
```

Das hier ist eine Trennung mit Trennstrich:
```
 be
<lb break="no"/>
zieht
```

--> in der HTML-Leseansicht sollte <lb break="no"/> als "-" erscheinen; sollte einmal eine Lemmatisierung erfolgen, dann sollte das Wort zusammengezogen werden zu "bezieht" (es können Leerzeichen vor und nach <...> sein)

**Comment by haoess** [comment]
Implementiert via bc5c9a9. Das macht den Bauprozess um Vieles langsamer, weil die Erkennung von Leerzeichen vor jedem `<lb/>` relativ teuer ist. Vermutlich ist es sinnvoll, einmal komplett in allen Quellen Leerzeichen vor und nach `<lb/>` zu ersetzen, dann kann der „langsame“ Code auch wieder raus.

Die „berechneten“ `-` werden [etwas abgeblasst](https://github.com/deutschestextarchiv/copadocs/blob/main/web/assets/css/tei.css#L62) dargestellt.

**Comment by maschiegg** [comment]
Aufgabe für @nina-bro : "Vermutlich ist es sinnvoll, einmal komplett in allen Quellen Leerzeichen vor und nach <lb/> zu ersetzen, dann kann der „langsame“ Code auch wieder raus."

**Comment by nina-bro** [comment]
habe jetzt die Leerzeichen in den Quellen vor und nach lb in den Quellen entfernt

**Comment by haoess** [comment]
Super, danke. Damit verkürzt sich der Bauprozess auch signifikant.
