### ISSUE TITLE
Einzelbrief: Anzeige

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#6]
Hier noch ein paar Optimierungsmöglichkeiten der Einzelbrief-Anzeige:

- 1 Die "fette Zeile" oben unter der Zeile "Start / kfb..." braucht es eigentlich nicht mehr, weil alle Infos detaillierter in der "Start..."-Zeile sind

- 2 Es wäre gut, wenn [#image_xxx] anklickbar wäre und das gleiche passiert, wie wenn man das Faksimile anklickt; bei sehr kleinen Monitoren verschwindet das Faksimile links, so kann man es noch aufrufen

- 3 Statt [#image_xxx] könnte stehen [Seite 1], [Seite 2] etc. Dass wir die Bilder durchnummeriert haben, ist für einen Nutzer der Website nicht unbedingt wichtig. Unter den Vorschaubildern finde ich "Faksimile #image_008" aber weiterhin sinnvoll. Es gibt aber auch Problemfälle, wenn mehr als 1 Faksimile einer Seite zugeordnet sind (z.B. wenn die Seite sehr groß ist, habe ich 2 Fotos gemacht, https://deutschestextarchiv.github.io/copadocs/kfb_00373_n_m_rotgerber_1842_1882_po1-so1/kfb_00373_n_so-concertbericht_1882_06_26-28.html). Da könnte dann z.B. stehen [Seite 1, Foto 1], [Seite 2, Foto 2].

- 4 Rechts neben dem Text ist noch eine hellgraue Box. Ist diese nötig oder könnte man den Platz besser für Text/Faksimile nutzen? Das Faksimile verschwindet nämlich schon, wenn die Monitorbreite kleiner als ca. 1000 Pixel wird

- 5 Ob das Folgende irgendwie technisch möglich ist, weiß ich nicht: Die Maximalbreite des Textes ist teilweise so breit, dass rechtsbündiger Text sehr weit rechts erscheint (z.B. https://deutschestextarchiv.github.io/copadocs/kfb_00120_h_f_zimmermannstochter_1834_1854-58_pp4-po2-ap2-ao8-so1/kfb_00120_h_ao_ca1854-58.html). Es wäre schön, wenn das nicht so auseinandergezerrt wird.

- 6 seg ana="#pic"[Strichmännchen] /seg  ->  könnte durch irgendein Symbol dargestellt werden und bei Mouseover erscheint der Text "Strichmännchen" (das ist eine kleine Zeichnung, die wir so annotieren) (siehe https://deutschestextarchiv.github.io/copadocs/kfb_01623_g_m_zimmergeselle_1851_1874-1905_pp15-po6-so1/kfb_01623_g_pp_1894_07_17.html)

**Comment by haoess** [comment]
> * 1 Die "fette Zeile" oben unter der Zeile "Start / kfb..." braucht es eigentlich nicht mehr, weil alle Infos detaillierter in der "Start..."-Zeile sind

Auskommentiert via 89cfbd3, aber das ist ungünstig, weil die Seite so keine Überschrift mehr hat (für Menschen mit Screenreadern, für den Impact bei Suchmaschinen). Wir brauchen eine gute Überschrift pro Seite. Die Breadcrumb-Navigation allein kann das nicht leisten.

> * 2 Es wäre gut, wenn [#image_xxx] anklickbar wäre und das gleiche passiert, wie wenn man das Faksimile anklickt; bei sehr kleinen Monitoren verschwindet das Faksimile links, so kann man es noch aufrufen

Ist nun so via 8e3d671.

> * 3 Statt [#image_xxx] könnte stehen [Seite 1], [Seite 2] etc. Dass wir die Bilder durchnummeriert haben, ist für einen Nutzer der Website nicht unbedingt wichtig. Unter den Vorschaubildern finde ich "Faksimile #image_008" aber weiterhin sinnvoll.

Ist nun so via 8e3d671.

> Es gibt aber auch Problemfälle, wenn mehr als 1 Faksimile einer Seite zugeordnet sind (z.B. wenn die Seite sehr groß ist, habe ich 2 Fotos gemacht, https://deutschestextarchiv.github.io/copadocs/kfb_00373_n_m_rotgerber_1842_1882_po1-so1/kfb_00373_n_so-concertbericht_1882_06_26-28.html). Da könnte dann z.B. stehen [Seite 1, Foto 1], [Seite 2, Foto 2].

Ist komplizierter, schau ich mir später an.

> * 4 Rechts neben dem Text ist noch eine hellgraue Box. Ist diese nötig oder könnte man den Platz besser für Text/Faksimile nutzen? Das Faksimile verschwindet nämlich schon, wenn die Monitorbreite kleiner als ca. 1000 Pixel wird

Bleibt auch erstmal offen.

> * 5 Ob das Folgende irgendwie technisch möglich ist, weiß ich nicht: Die Maximalbreite des Textes ist teilweise so breit, dass rechtsbündiger Text sehr weit rechts erscheint (z.B. https://deutschestextarchiv.github.io/copadocs/kfb_00120_h_f_zimmermannstochter_1834_1854-58_pp4-po2-ap2-ao8-so1/kfb_00120_h_ao_ca1854-58.html). Es wäre schön, wenn das nicht so auseinandergezerrt wird.

Drin via f6cd105996ffc. Perfekt wird das nicht werden, aber es ist besser als vorher.

> * 6 seg ana="#pic"[Strichmännchen] /seg  ->  könnte durch irgendein Symbol dargestellt werden und bei Mouseover erscheint der Text "Strichmännchen" (das ist eine kleine Zeichnung, die wir so annotieren) (siehe https://deutschestextarchiv.github.io/copadocs/kfb_01623_g_m_zimmergeselle_1851_1874-1905_pp15-po6-so1/kfb_01623_g_pp_1894_07_17.html)

Drin via 880a167.


Gern Einzeltickets pro Anliegen aufmachen: Manchmal ist der Sachverhalt komplizierter, und es bleibt so übersichtlicher, danke!

**Comment by maschiegg** [comment]
Zu (1):  Die Überschrift könnte dann bleiben, evtl. in etwas kleinerer Schrift als zuvor und mit Info von der Breadcrumb-Navigation, z.B. ao von Joseph S., 28.07.1851

**Comment by maschiegg** [comment]
Zu (1): Habe die Überschrift wieder hergestellt, nun in etwas kleinerer Schrift und mit "Text von" eingeleitet [[2d62485](https://github.com/deutschestextarchiv/copadocs/commit/2d624858eb858eef62c2b01959a23457c8030135)]
