### ISSUE TITLE
Navigationsleiste

### ISSUE THREAD

**Issue by maschiegg** [deutschestextarchiv/copadocs#8]
In der Navigationsleiste sollte statt "Übersicht Briefe" besser "Gesamtkorpus" stehen (es gibt auch andere Textsorten als Briefe), rechts daneben könnte der Link zu "Patientenakten" eingefügt werden.

Der Titel bei https://deutschestextarchiv.github.io/copadocs/list.html sollte dann auch "Gesamtkorpus" lauten.

Die Links zu DTA und Start sind noch identisch. Der zu DTA sollte eigentlich zu https://deutschestextarchiv.de/ führen?

**Comment by haoess** [comment]
Ist geändert. Bitte auch immer die mobile Ansicht mit beachten (ist nun auch wieder ok).
